### ISSUE TITLE
script running error

### ISSUE THREAD

**Issue by oUp2Uo** [RuojinCai/doppelgangers#19]
Hi, thanks for the work.

I tried to run the script `script_sfm_disambiguation.py` with or without existed database.
And I got similar error like:

```
Extracting loftr matches
Traceback (most recent call last):
  File "script_sfm_disambiguation.py", line 237, in <module>
    main()
  File "script_sfm_disambiguation.py", line 233, in main
    main_worker(args.gpu, ngpus_per_node, cfg, args)
  File "script_sfm_disambiguation.py", line 179, in main_worker
    pair_path = create_image_pair_list(args.database_path, args.output_path)
  File "D:\workspace\doppelgangers\doppelgangers\utils\process_database.py", line 64, in create_image_pair_list
    pairs, matches, _, _, _, pairs_id = read_two_view_from_db(db_path)
  File "D:\workspace\doppelgangers\doppelgangers\utils\process_database.py", line 33, in read_two_view_from_db
    qvec = blob_to_array(qvec, np.float64)
  File "D:\workspace\doppelgangers\doppelgangers\utils\database.py", line 134, in blob_to_array
    return np.fromstring(blob, dtype=dtype).reshape(*shape)
TypeError: a bytes-like object is required, not 'NoneType'
```

Do you have any idea about this?

I am using COLMAP 3.9.1, and run on Win 11.

Thank you.

**Comment by oUp2Uo** [comment]
It seems that it is a problem of the database, which is lack of some information.
